Remove unused/unneeded list vars and logic for packages and TPLs (#299, #63)
TriBITSPub/TriBITS pull request #531
Opened 2022-10-17 15:57 UTC by bartlettroscoe

## Description

This is a cleanup PR to allow the next step in working towards #63 (and removing some stuff not needed after the completion of #299).

See the individual commit messages for what was changed and why.

## Instructions for Reviewers

* Please review the commits individually (there are no intermediate commits with changes not reflected in the final diff).

2022-10-17 15:58 UTC, bartlettroscoe commented
Hello @KyleFromKitware, can you please give this PR a review when you get some time?

I will build my next branch off of this branch to continue work in the meantime.

2022-10-17 19:20 UTC, KyleFromKitware requested changes
Looks good, requested a few changes.

2022-10-17 19:20 UTC, KyleFromKitware commented on tribits/core/package_arch/TribitsSetUpEnabledOnlyDependencies.cmake
> +      if ("${lastExportTribitsPackage}" STREQUAL ${tribitsPackage})
Is `${tribitsPackage}` supposed to be quoted?

2022-10-17 19:20 UTC, KyleFromKitware commented on tribits/core/package_arch/TribitsSetUpEnabledOnlyDependencies.cmake
> +  foreach(DEP_PKG ${${PACKAGE_NAME}_LIB_REQUIRED_DEP_PACKAGES})
`IN LISTS`

2022-10-17 19:20 UTC, KyleFromKitware commented on tribits/core/package_arch/TribitsSetUpEnabledOnlyDependencies.cmake
> +  foreach(DEP_PKG ${${PACKAGE_NAME}_LIB_OPTIONAL_DEP_PACKAGES})
`IN LISTS`

2022-10-17 19:20 UTC, KyleFromKitware commented on tribits/core/package_arch/TribitsSetUpEnabledOnlyDependencies.cmake
> +    foreach(DEP_PACKAGE  ${PACKAGE_FULL_DEPS_LIST})
`IN LISTS`

2022-10-17 19:20 UTC, KyleFromKitware commented on tribits/core/package_arch/TribitsSetUpEnabledOnlyDependencies.cmake
> +  foreach(DEP_PACKAGE  ${PACKAGE_FULL_DEPS_LIST})
`IN LISTS`

2022-10-17 19:20 UTC, KyleFromKitware commented on tribits/core/package_arch/TribitsSetUpEnabledOnlyDependencies.cmake
> +    foreach(SORTED_PACKAGE  ${ORDERED_PACKAGE_FULL_DEPS_LIST})
`IN LISTS`

2022-10-18 13:02 UTC, bartlettroscoe commented
Hello @KyleFromKitware, all of the issues you raised in your review [above]() should be addressed in the new commit https://github.com/TriBITSPub/TriBITS/pull/531/commits/35d2b978ab2e0b4b43fd5b52f777317f3f1ba4d3.  Can you please re-review and approve if issues are addressed?

2022-10-18 14:28 UTC, merged