Allow specifying FIND_SHARED_LIBS per-TPL
TriBITSPub/TriBITS pull request #624
Opened 2024-12-17 02:52 UTC by sebrowne

Currently we (Trilinos) wish to be able to find all TPLs statically...except for some which we must find shared, because static installations do not exist in the environment we're using.  For example, we want to use "all" static TPLs for our CUDA build, but the installation of METIS is only shared.  Currently, this is done by setting `TPL_FIND_SHARED_LIBS` to `OFF`, and specifying `METIS_LIBRARIES` to be the explicit full path to `libmetis.so`.  This unfortunately bypasses the 'finding' of METIS.  It would be nicer if we could pass `-DTPL_FIND_SHARED_LIBS=OFF -DMETIS_FIND_SHARED_LIBS=ON` and have TriBITS continue to do the same thing for each TPL, by finding METIS as normal (eliminates some brittleness in our configuration management).

I looked at doing this, and the code change seems fairly trivial unless I'm missing something.  I added a test as well.

2024-12-17 17:36 UTC, sebrowne commented
@bartlettroscoe no particular rush on this, but I'd appreciate a review whenever you have the time.

2024-12-17 18:02 UTC, bartlettroscoe requested changes
@sebrowne, thanks for the PR.  This is a very reasonable extension.  And thanks for adding the test case!  (If you revert the change to the *.cmake file, does the test fail?  Hopefully yes but it is worth checking.)

Just a coupe of things should be addressed before merging:

1. The logic for how the var ??? is set should be tweaked (see below)
2. This needs to be documented somehow.  I might suggest adding a mention of this variable to the section [Building static libraries and executables](https://raw.githubusercontent.com/TriBITSPub/TriBITS/refs/heads/master/tribits/doc/build_ref/TribitsBuildReferenceBody.rst)?  (Or it could be a new subsection?)

2025-02-19 17:38 UTC, sebrowne commented on tribits/core/package_arch/TribitsTplFindIncludeDirsAndLibraries.cmake
> +  if (NOT DEFINED ${TPL_NAME}_FIND_SHARED_LIBS)
Done

2025-02-19 17:43 UTC, sebrowne commented
@bartlettroscoe  applied your suggestion for 1., and added a blurb of documentation for 2.

2025-02-19 18:47 UTC, bartlettroscoe approved these changes
Looks great.  Thanks!

2025-02-19 18:49 UTC, bartlettroscoe commented
FYI: The GHA checks are fixed in the PR #626.  I will pull those checks off into their own PR and merge it so that it will allow this and other tests to pass.

2025-02-19 20:37 UTC, merged

2025-02-19 20:39 UTC, bartlettroscoe commented
@sebrowne, if urgent, I can setup snapshot/merge to Trilinos 'develop'.  Otherwise, I will soon merge #626 and snapshot/merge TriBITS 'master' (including this PR) to Trilinos 'develop' in the next few days (after testing by the STK project).

2025-02-19 20:46 UTC, sebrowne commented
> @sebrowne, if urgent, I can setup snapshot/merge to Trilinos 'develop'. Otherwise, I will soon merge #626 and snapshot/merge TriBITS 'master' (including this PR) to Trilinos 'develop' in the next few days (after testing by the STK project).

Waiting is a-okay with me, no rush.  I'll start using it once it's in, but I can manage perfectly fine until then.